
###
POST http://localhost:8080/rest/form/demo
Content-Type: application/x-www-form-urlencoded

name=zhangsan&age=90&content=new-element

###
POST http://localhost:8080/rest/json/demo
Content-Type: application/json

{
  "name": "lisi",
  "age": 100,
  "content": "content"
}
