POST http://localhost:8080/adduser
Content-Type: application/json

{
  "username": "张三",
  "password": "qwer123"
}

### adduser2
POST http://localhost:8080/adduser2
Content-Type: application/json

{
  "username": "张三",
  "password": "qwer123"
}
###
POST http://localhost:8080/adduser3
Content-Type: application/json

{
  "username": "张三",
  "password": "qwer123"
}