
###
GET http://localhost:8080/listener/user

###
GET http://localhost:8080/listener/total

###
GET http://localhost:8080/listener/total2

###
GET http://localhost:8080/listener/request

###
GET http://localhost:8080/listener/publish